app:
    resource: '@AppBundle/Controller'
    type: annotation

api_addresses:
    type:     rest
    prefix: api
    resource: AppBundle\Controller\ApiAddressesController

logout:
    path: /logout

